config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root 'static#home'

  get '/about',   to: "static#about",   as: "about"
  get '/contact', to: "static#contact", as: "contact"
  get '/faq',     to: "static#faq",     as: "faq"
  get '/workers', to: "static#workers", as: "workers"
  get '/hire',    to: "jobs#new",       as: "hire"

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id             :integer          not null, primary key
#  first_name     :string(255)
#  last_name      :string(255)
#  email          :string(255)
#  phone          :string(255)
#  description    :string(255)
#  workers_needed :integer
#  date           :datetime
#  english_level  :string(255)
#  how_hear       :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Job < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:first_name, :last_name, :email, :phone, :description, :workers_needed, :date, :english_level, :how_hear)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home

  end

  def faq

  end

  def hire

  end

  def about

  end

  def workers

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_form.html.haml
= bootstrap_form_for @job do |f|
  = f.text_field :first_name
  = f.text_field :last_name
  = f.email_field :email
  = f.phone_field :phone
  = f.text_area :description
  = f.number_field :workers_needed
  = f.datetime_select :date
  = f.select :english_level, options_for_select(["Basic English", "Fluent English", "Not Necessary"]), :include_blank => true
  = f.select :how_hear, options_for_select(["Online", "Flier", "Friend", "TV"]), include_blank: true, label: "How did you hear about us?"
  = f.submit "Submit"

app/views/jobs/new.html.haml
- @title = "Hire | DLP"
.section-colored
  .container
    .row
      .col-xs-12
        %h1.text-center Hire A Worker
.section
  .container
    .row
      .col-xs-12
        .col-xs-6.col-xs-offset-3
          = render 'form'
        .col-xs-12
          %p Or You can also hire by calling(415)252-5375.
          %br
          %p If you call during office hours we can dispatch a worker with as little as an hours' notice. Workers are available 7 days a week, at all hours.

app/views/layouts/_footer.html.haml
.container
  %hr
  %footer
    .row
      .col-lg-12
        %p= "Donated SF Day Labor Program Website. All rights reserved © #{Time.now.year}"

app/views/layouts/_top_navbar.html.haml
%nav.navbar{role: "navigation", style:"margin-bottom:0px;"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      / You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it)
      =link_to "SF Day Labor Program", root_path, :class => "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right

        %li
          =link_to "Hire", hire_path
        %li
          =link_to "Our Workers", workers_path
        %li
          =link_to "Contact", contact_path
        %li
          =link_to "FAQ", faq_path
        %li
          =link_to "About", about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @title || 'Day Labor Program'
    %meta{ :name => "description", :content => @description || "We are a worker-lead nonprofit committed to improving your life and the life of our members. We pride ourselves on having hard-working, reliable workers."}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render "layouts/top_navbar.html.haml"
    = yield
    = render "layouts/footer"